### ISSUE TITLE
Is it possible to build an agent's workflow entirely from a JSON definition at runtime?

### ISSUE THREAD

**Issue by fabrifls** [i-am-bee/beeai-framework#857]
Hi! Thanks a lot for this excellent framework.

I'm currently working on a platform that includes a visual builder (UI) to design AI agent workflows as node trees — similar to a flowchart of steps, tool calls, and LLM prompts. These are then serialized to JSON.

The goal is to take that JSON and instantiate a complete agent workflow dynamically at runtime using `beeai-framework`.

I've been looking through the documentation and source code, but couldn't find a clear way to do this — especially for fully defining the steps, tools, and execution flow from JSON only.

Specifically:

- Can steps (e.g. `llm_call`, `tool_call`, `if`, `map`) be registered dynamically from a parsed JSON definition?
- Is there any helper like `Agent.fromJSON()` or `agentFromDefinition()` planned or available?
- What's the recommended pattern to load a dynamic flow into an `Agent` class if not supported directly?
- Are there any examples of runtime-defined or interpreted workflows?

The use case is similar to a low-code/no-code platform for dynamic AI agents, using `beeai-framework` as the runtime engine.

Thanks in advance!

**Comment by Tomas2D** [comment]
Hello @fabrifls, we are glad you like the framework.

The serialization is done in the TS version only (`Agent.fromSerialized(...)`, `agent.serialize()`). In Python version, one can try to play with the pickle module.

Regarding the low-code / no-code, we are now at the beginning of bringing this ability to the framework (starting in the  Python version). You will be able to define a set of YAMLs and let the framework convert them to live classes.

Example

```yaml
name: 'WeatherAgent'
id: 'weather-agent'
creator: 'Bee AI'
based_on: 'ToolCallingAgent'
description: 'My agent'
version: '0.1'
config:
   # 1:1 mapping to agent's constructor arguments
   llm: $ollama_granite31_chat_model
   tools:
     - $weather_tool
     - $duckduckgo_search_tool 
   memory: $my_memory
   save_intermediate_steps: true

   # definition of relevant classes
  $ollama_granite31_chat_model:
    type: OllamaChatModel
    arguments:
      model_id: llama3.1
      parameters:
        temperature: 0.1

  $weather_tool:
    type: OpenMeteoTool
    arguments: {}

  $duckduckgo_search_tool:
    type: DuckDuckGoSearchTool
    arguments: {}

  $my_memory:
    type: UnconstrainedMemory
    arguments: {}
```

```python
loader = Loader()
loader.load("weather_agent.yaml")

agent = loader.get(WeatherAgent)
await agent.run(...)
```
